vim.keymap.set('n', '<leader>tt', function ()
	vim.cmd.tag(vim.fn.expand("<cword>"))
end, {})
vim.keymap.set('n', '<leader>tr', function ()
	vim.cmd.helptags("./")
	print("regenerated tags")
end, {})
